const fhirData = $('Extract Report ID').item.json;
const diagData = $('Build FHIR Diagnostic Report').item.json;
const variants = $('Aggregate Variants').item.json.variants;

const pathogenicCount = diagData.pathogenic_count;
const passCount = diagData.pass_count;
const totalCount = diagData.observation_count;
const sampleId = diagData.sample_id;
const patientId = diagData.patient_id;
const genomeBuild = diagData.genome_build;
const reportUrl = fhirData.fhir_server_report_id ? `https://hapi.fhir.org/baseR4/DiagnosticReport/${fhirData.fhir_server_report_id}` : '#';

const variantRows = variants.map((v, i) => {
  const isPathogenic = ['pathogenic', 'likely_pathogenic'].includes(v.clinical_significance);
  const sigStyle = isPathogenic ? 'color: #fc8181; font-weight: bold;' : 'color: #a0aec0;';
  return `<tr>
    <td>${i+1}</td>
    <td>chr${v.chrom}:${v.pos}</td>
    <td>${v.ref} &rarr; ${v.alt}</td>
    <td style="${sigStyle}">${v.clinical_significance.replace(/_/g, ' ')}</td>
    <td>${v.filter}</td>
    <td>${v.clinvar_uid ? `<a href="https://www.ncbi.nlm.nih.gov/clinvar/variation/${v.clinvar_uid}/" target="_blank" style="color:#63b3ed;">${v.clinvar_uid}</a>` : 'N/A'}</td>
  </tr>`;
}).join('');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>VCF to FHIR Clinical Report — ${sampleId}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           background: #0f1117; color: #e2e8f0; padding: 2rem; }
    .container { max-width: 1100px; margin: 0 auto; }
    header { background: linear-gradient(135deg, #1a1f2e, #2d3748);
             border: 1px solid #4a5568; border-radius: 12px;
             padding: 2rem; margin-bottom: 2rem; }
    header h1 { font-size: 1.8rem; color: #68d391; margin-bottom: 0.5rem; }
    .meta { display: flex; gap: 2rem; flex-wrap: wrap; margin-top: 1rem; }
    .meta-item { background: #2d3748; padding: 0.5rem 1rem;
                 border-radius: 8px; font-size: 0.85rem; }
    .meta-item span { color: #a0aec0; }
    .highlight { color: #f6ad55; font-weight: bold; }
    .alert { color: #fc8181; font-weight: bold; }
    section { background: #1a1f2e; border: 1px solid #2d3748;
              border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }
    section h2 { font-size: 1.2rem; color: #63b3ed; margin-bottom: 1rem;
                 padding-bottom: 0.5rem; border-bottom: 1px solid #2d3748; }
    table { width: 100%; border-collapse: collapse; font-size: 0.88rem; }
    th { background: #2d3748; color: #a0aec0; text-align: left;
         padding: 0.6rem 0.8rem; font-weight: 600; text-transform: uppercase;
         font-size: 0.75rem; letter-spacing: 0.05em; }
    td { padding: 0.6rem 0.8rem; border-bottom: 1px solid #2d3748; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #2d3748; }
    a { color: #63b3ed; text-decoration: none; }
    a:hover { text-decoration: underline; }
    footer { text-align: center; color: #4a5568; font-size: 0.8rem; margin-top: 2rem; }
  </style>
</head>
<body>
<div class="container">
  <header>
    <h1>Clinical Genomics ETL Report</h1>
    <div class="meta">
      <div class="meta-item"><span>Patient ID: </span><span class="highlight">${patientId}</span></div>
      <div class="meta-item"><span>Sample ID: </span><span class="highlight">${sampleId}</span></div>
      <div class="meta-item"><span>Genome Build: </span>${genomeBuild}</div>
      <div class="meta-item"><span>FHIR Report: </span><a href="${reportUrl}" target="_blank">View on HAPI</a></div>
      <div class="meta-item"><span>Generated: </span>${new Date().toLocaleString()}</div>
    </div>
  </header>

  <section>
    <h2>Variant Summary</h2>
    <div class="meta" style="margin-top: 0;">
      <div class="meta-item"><span>Total Variants: </span>${totalCount}</div>
      <div class="meta-item"><span>Quality PASS: </span>${passCount}</div>
      <div class="meta-item"><span class="${pathogenicCount > 0 ? 'alert' : ''}">Pathogenic/LP: </span><span class="${pathogenicCount > 0 ? 'alert' : ''}">${pathogenicCount}</span></div>
    </div>
  </section>

  <section>
    <h2>Variant Details (ClinVar Enriched)</h2>
    <table>
      <thead><tr><th>#</th><th>Position</th><th>Mutation</th><th>Significance</th><th>Filter</th><th>ClinVar UID</th></tr></thead>
      <tbody>
        ${variantRows}
      </tbody>
    </table>
  </section>

  <footer>Generated by VCF to FHIR ETL Pipeline · n8n · ${new Date().getFullYear()}</footer>
</div>
</body>
</html>`;

return [{ json: { html } }];